name: Cloudový Motor (SEC, Dataroma, Insider)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  aktualizace:
    runs-on: ubuntu-latest
    steps:
      - name: Stáhnout kód repozitáře
        uses: actions/checkout@v3

      - name: Nastavit Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalace knihoven
        run: |
          pip install pandas requests cloudscraper yfinance beautifulsoup4 lxml

      - name: Nastavení Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Spuštění SEC motoru a stažení tržních dat
        run: python sec_updater.py
        - name: Spuštění všech motorů (SEC, Dataroma, Insiders)
        run: |
          python sec_updater.py
          python 2_Superinvestors_13F
          python 1_Insider_4F
        
      # (Pokud máš i skript na Dataromu/Insidery, můžeš ho přidat pod tento řádek)
      # run: python tvuj_skript_na_insidery.py
